---
title: "title"
subtitle: "subtitle"
author:
- Andrii Voitkiv
date: "`r format(Sys.time(), '%a, %b %d, %Y')`"
geometry: margin=3cm
output:
    html_document:
        css: /Users/berg/DataspellProjects/MDSA-UofC/DATA605/10_project/style.css
        toc: true
        toc_float: false
        toc_depth: 3
        number_sections: false
        fig_width: 16
        fig_height: 8
        fig_retina: 6
        fig_path: Figs/
        keep_md: false
        theme: spacelab
        highlight: tango # pygments, kate, espresso, zenburn, haddock, textmate
---
```{r}
library(dplyr)
library(pins)
library(ggplot2)
library(png)
```
```{r}
# Data
board <- board_folder("/Users/berg/DataspellProjects/MDSA-UofC/DATA605/10_project/pins")
RT_hourly <- pin_read("RT_hourly", board = board)
# Icons
img_path <- "/Users/berg/DataspellProjects/MDSA-UofC/DATA605/10_project/icons"
```

```{r}
start_date <- as.Date("2018-01-01")
end_date <- as.Date("2022-12-31")
unique_hours <- as.numeric(difftime(end_date, start_date, units = "hours")) / 24
length_days <- as.numeric(difftime(end_date, start_date, units = "days"))
```

```{r}
# Productivity colors from Rescue Time app:----
Productivity_col <- rgb(red = c(13, 65, 177, 218, 212, 160),
                        green = c(88, 130, 193, 105, 28, 235),
                        blue = c(193, 221, 191, 93, 21, 142),
                        names = c("Very Productive", "Productive", "Neutral",
                                  "Distracting", "Very Distracting", "Mobile Phone"),
                        maxColorValue = 255)
colors <- Productivity_col[c("Productive", "Very Distracting")]
```

```{r}
# Group by Category and Productivity. Summarize by Duration
RT_by_category <- RT_hourly %>%
  group_by(Category, Productivity) %>%
  dplyr::summarize(Duration = sum(Duration) / length_days / 60) %>%
  mutate(Productivity = case_when(
    Productivity == 2 ~ "Very Productive",
    Productivity == 1 ~ "Productive",
    Productivity == 0 ~ "Neutral",
    Productivity == -1 ~ "Distracting",
    Productivity == -2 ~ "Very Distracting"),
         # Productivity = factor(Productivity, levels = c("Very Productive", "Productive", "Neutral", "Distracting", "Very Distracting")),
         Category = factor(Category, levels = c("Business", "Communication & Scheduling", "Design & Composition", "Entertainment", "iOS Device", "News & Opinion","Reference & Learning", "Shopping", "Social Networking", "Software Development", "Uncategorized", "Utilities")),
         Total_Duration = sum(Duration)
  )
# Convert Productivity to factor
RT_by_category$Productivity <- factor(RT_by_category$Productivity, levels = c("Very Productive", "Productive", "Neutral", "Distracting", "Very Distracting"))
# Arrange by Total Duration in descending order
RT_by_category <- RT_by_category %>%
  arrange(desc(Total_Duration))
```

```{r}
make.donut <- function(df, category){

  subset <- df %>%
    filter(Category == category) %>%
    mutate(fraction = Duration / sum(Duration))

  par(mar = c(2, 0, 0, 0), xaxs = "i", yaxs = "i", family = "Comfortaa")

  pie(subset$fraction, clockwise = TRUE,
      col = Productivity_col[-6][unique(as.character(subset$Productivity))],
      border = "white",labels = NA, xlim = c(-0.7, 0.7), ylim = c(-0.7, 0.7))
  symbols(0,0, circles = 0.35, fg = "white", bg = "white",
          add = TRUE, inches = FALSE)
  text(0, -0.9, labels = category, font = 2, col = "grey20",
       cex = 1, adj=c(0.5, 1), xpd = TRUE)
  # print(round(unique(subset$Total_Min_Duration)))
  text(0, -1, paste0("\n(", round(unique(subset$Total_Duration)), " min/day)"),
       col = "grey20", cex = 1, adj=c(0.5, 1), xpd = TRUE)
}

h_title <- 1.5
h_legend <- 1.8

layout(matrix(c(rep(1, 4), rep(2, 4), 3:14), nrow = 5, ncol =  4, byrow = TRUE),
       heights = lcm(c(h_title, h_legend)))

# first plot is a title + subtitle
par(mar = c(0, 0, 0, 0), family = "Comfortaa")
plot.new()
text(0, 1, "Productivity pulse of the 12 main Categories",
     adj = c(0, 1.1), col = "grey20", font = 2, cex = 2, xpd = TRUE)
text(0, 0, paste0("Measured with RescueTime (", length_days, " days)"),
     adj = c(0, -0.1), col = "grey30", cex = 1.5, xpd = TRUE)

# second plot is the legend:
par(mar = c(0, 0, 0, 0))
plot.new()
legend(0.5, 0.5, legend = levels(RT_by_category$Productivity),
       fill = Productivity_col[levels(RT_by_category$Productivity)],
       title.adj = 0, title.col = "grey20",
       y.intersp = 1.2, text.col = "grey30",
       border = "transparent", ncol=2,
       cex = 1.2, xjust = 0.5, yjust = 0.5, bty = "n", xpd = TRUE)

#
ordered_cats <- RT_by_category %>%
  group_by(Category) %>%
  dplyr::summarize(Total_Duration = sum(Total_Duration)) %>%
  arrange(desc(Total_Duration)) %>%
  pull(Category)
# then add the individual donut plots:
library('tidyverse')
walk(ordered_cats, function(Category){
  image <- readPNG(file.path(img_path, paste0(
    gsub(" .*$", "", Category), ".png")))

  make.donut(df = RT_by_category, category = Category)
  rasterImage(image, xleft = -0.5, xright = 0.5, ybottom = -0.5, ytop = 0.5)
})
```
